### ISSUE TITLE
Releases missing

### ISSUE THREAD

**Issue by shtayerc** [LeelaChessZero/lczero-common#11]
Hello,

I am trying to package lc0 program for void linux. Repository [lc0](https://github.com/LeelaChessZero/lc0) has releases, but it pulls [lczero-common](https://github.com/LeelaChessZero/lczero-common) during configure - this is not prefered. One solution is to pull compressed archive from master like it is stated in README, but after new commit checksum would change. 

My request is if you could also create releases in this repository. The best would be if version numbers were the same.

**Comment by mooskagh** [comment]
I believe we could, but I'm not sure I understand the problem.
Do you fetch the Lc0 sources using `git clone` or download `.zip` file?

**Comment by shtayerc** [comment]
I download .tag.gz files. Every archive needs corresponding checksum. Problem is that when pulling archive from lczero-common master checksum will change at next commit. 
[Work in progress package template](https://github.com/shtayerc/void-packages/commit/496114b27e392061d85f828a0fd0bcc759b3f069#diff-8f7f05c06d6d503b760ba6c854088794R16)

**Comment by borg323** [comment]
Our lc0 build script only pulls in lczero-common (or downloads it) if it isn't there. If I understand your issue corectly, you can download/extract a fixed version and then you should be OK.

**Comment by shtayerc** [comment]
Yes, the only problem is that lczero-common does not have fixed version (releases would solve that).
Pulling archive from master is not fixed, it will change at new commits.

**Comment by borg323** [comment]
You can get download the archive for specific commits,  like <https://github.com/LeelaChessZero/lczero-common/archive/5b8667e4ab51e18b2ea26ac221723d6dd8f95533.tar.gz> for the current master.

**Comment by shtayerc** [comment]
I did not know that. This solves my problem. Thank you
